name: CICD

on:
  push:
    branches: [ main ]

jobs:
  generate-version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Github Tag Bump
      id: tab_bump
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.PUSH_NUGET }}     
        INITIAL_VERSION: 1.0.2
        DEFAULT_BUMP: patch
        
    outputs:
      new_version: ${{ steps.tab_bump.outputs.new_tag }}

  package-and-publish-contracts:

    runs-on: ubuntu-latest
    needs: generate-version

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
        source-url: https://nuget.pkg.github.com/SoulCupid/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.PUSH_NUGET }} 
        
    - name: Pack
      run: | 
        dotnet pack src/DatingApp.Common/ \
        --configuration Release \
        -p:PackageVersion=${{ needs.generate-version.outputs.new_version }} \
        -p:RepositoryUrl=https://github.com/SoulCupid/DatingApp.Common \
        -o packages

    - name: Publish
      run: dotnet nuget push packages/*.nupkg --api-key ${{ secrets.PUSH_NUGET }} --source https://nuget.pkg.github.com/SoulCupid/index.json
